// This file is generated by Slice Machine. Update with care!

import Benefits from './Benefits';
import CallToAction from './CallToAction';
import Hero from './Hero';
import Images from './Images';
import Logos from './Logos';
import NavLinks from './NavLinks';
import Projects from './Projects';
import RichText from './RichText';
import TeamMembers from './TeamMembers';
import Testimonial from './Testimonial';

export {
	Benefits,
	CallToAction,
	Hero,
	Images,
	Logos,
	NavLinks,
	Projects,
	RichText,
	TeamMembers,
	Testimonial,
};

export const components = {
	benefits: Benefits,
	call_to_action: CallToAction,
	hero: Hero,
	images: Images,
	logos: Logos,
	nav_links: NavLinks,
	projects: Projects,
	rich_text: RichText,
	team_members: TeamMembers,
	testimonials: Testimonial,
};
